routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\{UserController,BankAccountController,wallethistoryController};
use App\Http\Controllers\Admin\{AnalystController, AccountController, WalletController, AgentController, QuestionsController, AnswersController, CallLogController, AnalystProfileController, AnalystBannerController, VideosController, BannerController, ContestController, UserContestController, UserKycController, PostController,  UserGameController, PartnerController };

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::get('/terms', function () {
    return view('terms');
});



Auth::routes();

Route::get('/logcheck', [App\Http\Controllers\HomeController::class, 'logcheck']);
Route::post('/admin-login', [App\Http\Controllers\HomeController::class, 'logincheck'])->name('admin-login');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/otp-verification', [App\Http\Controllers\Auth\LoginController::class, 'checkOtp'])->name('checkOtp');
Route::post('/otp-verify', [App\Http\Controllers\Auth\LoginController::class, 'verifyOtp'])->name('verify-otp');
Route::get('/gms', [App\Http\Controllers\HomeController::class, 'testing']);
Route::get('/live', function () {
    return view('live');
});

Route::post('register',[UserController::class, 'register'])->name('user.register');

   //Start User Game play Route Here
   Route::group(['middleware' => ['auth', 'checkRole:User']], function () {
    Route::resource('user-game', UserGameController::class);
    Route::get('game/choose-game',[UserGameController::class, 'GameTypeView'])->name('GameTypeView');
    Route::get('game/game-history',[UserGameController::class, 'GameHistory'])->name('GameHistory');
    Route::get('game/wallet-history',[UserGameController::class, 'WalletHistory'])->name('WalletHistory');
    Route::post('game/addBallanceWallet',[UserGameController::class, 'addBallanceWallet'])->name('addBallanceWallet');
    Route::get('game/list',[UserGameController::class, 'GameList'])->name('GameList');
    Route::any('user/{id?}/play-game/{game_type?}',[UserGameController::class, 'playGameView'])->name('user.playGame');
    Route::post('user/play-gameStore',[UserGameController::class, 'playGameStore'])->name('user.playGame.store');
    Route::get('user/play-game/history',[UserGameController::class, 'playGameHistory'])->name('user.playGame.history');
    Route::get('user/play-game/dashboard/{id?}',[UserGameController::class, 'playGameDashboard'])->name('user.playGame.dashboard');

    Route::get('user/previous-game',[UserGameController::class, 'previousGame'])->name('user.previousGame');
});
//End User Game play Route Here

  //Start Partner Dashboard Route Here
  Route::group(['middleware' => ['auth', 'checkRole:Partner'], 'prefix' => 'partner'], function () {
    Route::get('dashboard', [PartnerController::class,'index'])->name('partner.dashboard');
    Route::get('game/create-game',[PartnerController::class, 'GameCreateView'])->name('partner.GameCreateView');
     Route::post('game/create-game',[PartnerController::class, 'GameCreateStore'])->name('partner.GameCreateStore');
    Route::get('game/game-history',[PartnerController::class, 'GameHistory'])->name('partner.GameHistory');
    Route::get('game/{id?}/settings',[PartnerController::class, 'GameSettings'])->name('partner.GameSettings');
    Route::get('/game',[PartnerController::class, 'DataFetch'])->name('partner.DataFetch');

});
//End Partner Dashboard Route Here


 //Start Agent Dashboard Route Here
 Route::group(['middleware' => ['auth', 'checkRole:Agent'], 'prefix' => 'agent'], function () {
     Route::get('dashboard', [AgentController::class,'index'])->name('agent.dashboard');
     Route::get('game/create-user',[AgentController::class, 'UserCreateView'])->name('agent.UserCreateView');
     Route::post('game/create-user',[AgentController::class, 'UserCreateStore'])->name('agent.UserCreateStore');
     Route::get('game/edit-user/{user_id?}',[AgentController::class, 'UserEditView'])->name('agent.UserEditView');
     Route::post('game/edit-user/{user_id?}',[AgentController::class, 'UserEditStore'])->name('agent.UserEditStore');
     Route::get('game/user-history',[AgentController::class, 'UserHistory'])->name('agent.UserHistory');
     Route::post('game/delete-user/{user_id?}',[AgentController::class, 'UserDestroy'])->name('agent.UserDestroy');
});
//End Agent Dashboard Route Here

Route::group(['middleware' => ['auth', 'checkRole:Admin']], function () {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('analysts', AnalystController::class);
    Route::resource('videos', VideosController::class);
    Route::resource('contest', ContestController::class);
    Route::get('contest/uploda-result/{id?}', [ContestController::class, 'ContestUploadResult'])->name('contest.upload.result');
    Route::post('contest/uploda-result/{id?}', [ContestController::class, 'ContestUploadResultStore'])->name('contest.upload.result.store');
    Route::get('contest/aproved/{id?}', [ContestController::class, 'approveContest'])->name('contest.aproved');
    Route::get('prize/distribution', [ContestController::class, 'prizeDistribution'])->name('contest.prizedistribution');
    Route::get('prize/{id?}', [ContestController::class, 'prizeDistributionView'])->name('contest.prize');

    Route::get('contest-answer', [ContestController::class, 'contestAnswer'])->name('contest.answer');
    Route::get('contest-answer-edit/{id?}', [ContestController::class, 'editAnswer'])->name('contest.editanswer');
    Route::post('contest-answer-save/{id?}', [ContestController::class, 'saveContestAns'])->name('contest.editanswersave');
    Route::resource('user_contest', UserContestController::class);
    Route::resource('wallets', WalletController::class);
    Route::resource('user_kyc', UserKycController::class);
    Route::resource('post', PostController::class);
    Route::get('wallets/{wallet}', [WalletController::class, 'show'])->name('wallets.show');

    Route::get('videos/aproved/{id?}', [VideosController::class, 'approveVideos'])->name('videos.aproved');
    Route::get('analysts/aproved/{id?}', [AnalystController::class, 'approveAnalyst'])->name('analysts.aproved');
    Route::get('analyst/account', [AccountController::class, 'index'])->name('account.index');
    Route::get('notification', [ContestController::class, 'notificationView'])->name('notification.create');
    Route::get('notification-list', [ContestController::class, 'notificationList'])->name('notification.index');
    Route::get('leader-board', [ContestController::class, 'leaderBoardList'])->name('leaderboard');
    Route::get('winners', [ContestController::class, 'winnerList'])->name('winnerlist');
    //Start User Management Route Here
    //Route::resource('products', ProductController::class);
    Route::resource('questions', QuestionsController::class);
    Route::resource('answers', AnswersController::class);
    Route::resource('call-logs', CallLogController::class);
    Route::resource('profiles', AnalystProfileController::class);
    Route::resource('banners', AnalystBannerController::class);
    Route::resource('banner', BannerController::class);

});

//Start some common group route here
Route::group(['middleware' => ['auth', 'checkRole:User,Partner,Agent']], function () {
    Route::resource('bank-accounts', BankAccountController::class);
});


//End some common group route here

Route::get('matka/test', [VideosController::class, 'matkaTest']);
Route::get('base64ToString', [UserController::class, 'decodeBase64']);

app/Models/BankAccount.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class BankAccount extends Model
{
    use HasFactory, SoftDeletes;
    protected $table = 'bank_accounts';
    protected $guarded = [];
}

app/Http/Controllers/BankAccountController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Models\{User, UserDetail, BankAccount};
use DB;
use Auth;
use Exception;
use Response;
use Illuminate\Support\Str;
use Carbon\Carbon;

class BankAccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = BankAccount::where('user_id',auth()->user()->id)->get();
        return view('admin.bank-account.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.bank-account.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'account_holder_name' => 'required|string|max:255',
            'account_number' => 'required|string|max:20|unique:bank_accounts',
            'ifsc_code' => 'required|string|max:11',
            // Add other validation rules as needed
        ]);
        DB::beginTransaction();
        try {
            $data = [
                'user_id' => auth()->user()->id,
                'account_holder_name' => $request->account_holder_name,
                'account_number' => $request->account_number,
                'ifsc_code' => $request->ifsc_code
            ];
            $query = BankAccount::create($data);
             DB::commit();
             return redirect()->route('bank-accounts.index')->with('success','Bank Added successfully !');
        } catch (\Throwable $th) {
             DB::rollback();
            //echo $th ;die;
            return back()->with('danger','Something went wrong');
        } 
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\BankAccount  $bankAccount
     * @return \Illuminate\Http\Response
     */
    public function show(BankAccount $bankAccount)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\BankAccount  $bankAccount
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = BankAccount::find($id);
        //dd($data);
        return view('admin.bank-account.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\BankAccount  $bankAccount
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
{
    $request->validate([
        'account_holder_name' => 'required|string|max:255',
        'account_number' => 'required|string|max:20|unique:bank_accounts,account_number,' . $id,
        'ifsc_code' => 'required|string|max:11',
        // Add other validation rules as needed
    ]);

    DB::beginTransaction();
    try {
        $data = [
            'account_holder_name' => $request->account_holder_name,
            'account_number' => $request->account_number,
            'ifsc_code' => $request->ifsc_code
        ];

        $query = BankAccount::where('id', $id)->update($data);
        DB::commit();

        return redirect()->route('bank-accounts.index')->with('success', 'Bank Updated successfully!');
    } catch (\Throwable $th) {
        DB::rollback();
        return back()->with('danger', 'Something went wrong');
    }
}

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\BankAccount  $bankAccount
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            BankAccount::find($id)->delete();
            return back()->with('danger','Bank Details deleted successfully');
        } catch (\Throwable $th) {
            return back()->with('danger','Something went wrong !');
        }
    }
}

resources/views/admin/bank-account/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0" />
  <title>Add Bank Account</title>

<!-- Favicons -->
<link rel="shortcut icon" href="{{ asset('game/assets/img/favicon.png') }}">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{{ asset('game/assets/plugins/bootstrap/css/bootstrap.min.css') }}">

<!-- Fontawesome CSS -->
<link rel="stylesheet" href="{{ asset('game/assets/plugins/fontawesome/css/fontawesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('game/assets/plugins/fontawesome/css/all.min.css') }}">

<!-- Animate CSS -->
<link rel="stylesheet" href="{{ asset('game/assets/css/animate.min.css') }}">

<!-- Main CSS -->
<!-- <link rel="stylesheet" href="{{ asset('game/assets/css/admin.css') }}"> -->
<link rel="stylesheet" href="{{ asset('game/assets/css/admin.css') }}">
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/bootstrap-datepicker.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/jquery.timepicker.css')}}"/>
</head>

<body>
  <div class="main-wrapper">
    <div class="header">
      <div class="header-left">
      </div>
       <a href="javascript:void(0);" id="toggle_btn">
         <i class="fas fa-align-left"></i>
      </a>
      <a class="mobile_btn" id="mobile_btn" href="javascript:void(0);">
         <i class="fas fa-align-left"></i>
      </a>
      <h3>Add Bank Account</h3>

      <ul class="nav user-menu">
        <li class="nav-item dropdown noti-dropdown">
          <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
          </a>
        </li>
        <li class="nav-item dropdown">
          <a href="javascript:void(0)" class="dropdown-toggle user-link nav-link" data-bs-toggle="dropdown">
            <h4>Profile</h4>
          </a>
        </li>

      </ul>
    </div>
    <!-- /Header -->

    @switch(true)
        @case(Auth::user()->hasRole('User'))
            @include('layouts.user_game.sidebar')
            @include('layouts.user_game.flash_msg')
            @break
        @case(Auth::user()->hasRole('Agent'))
            @include('layouts.agent.sidebar')
            @include('layouts.agent.flash_msg')
            @break
        @case(Auth::user()->hasRole('Partner'))
            @include('layouts.partner.sidebar')
            @include('layouts.partner.flash_msg')
    @endswitch
    <div class="page-wrapper">

      <div class="content container-fluid">
        
      <div class="row">
					<div class="col-xl-8 offset-xl-2">
					
						<!-- Page Header -->
						<div class="page-header">
							<div class="row">
								<div class="col-sm-12">
                <a href="{{ route('bank-accounts.index') }}" type="button" class="btn btn-success bg-info" title="edit">Go Back</a>
								</div>
							</div>
						</div>
						<!-- /Page Header -->
						
						<div class="card">
							<div class="card-body">
							
								<!-- Form -->
								<form action="{{ route('bank-accounts.store') }}" method="post">
                  @csrf
                  <div class="row">
                     <div class="col-sm-12">
                        <div class="form-group">
                        <label>A/C Number</label>
                        <input class="form-control account_number" name="account_number" type="text" Placeholder="A/C Number" value="{{old('account_number')}}" required>
                        @error('account_number')
                              <li style="color:#e71814">{{ $message }}</li>
                        @enderror
                        </div>
                     </div>
									</div>

                  <div class="row">
                     <div class="col-sm-12">
                        <div class="form-group">
                        <label>Ifsc Code</label>
                        <input class="form-control" name="ifsc_code" type="text" Placeholder="Ifsc Code" value="{{old('ifsc_code')}}" required>
                        @error('ifsc_code')
                              <li style="color:#e71814">{{ $message }}</li>
                        @enderror
                        </div>
                     </div>
									</div>

                  <div class="row">
                     <div class="col-sm-12">
                        <div class="form-group">
                        <label>A/C Holder Name</label>
                        <input class="form-control" name="account_holder_name" type="text" Placeholder="A/C Holder Name" value="{{old('account_holder_name')}}" required>
                        @error('account_holder_name')
                              <li style="color:#e71814">{{ $message }}</li>
                        @enderror
                        </div>
                     </div>
									</div>

									<div class="mt-4">
										<button class="btn btn-primary" type="submit">Submit</button>
										<button class="btn btn-primary" type="reset">Reset</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>

      </div>
    </div>
  </div>
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header justify-content-center">
          <h5 class="modal-title" id="staticBackdropLabel">Select Game</h5>

        </div>
        <div class="modal-body">
          <div class="row">
            <div class="game">
              <div class="col-lg-12 col-md-12 col-sm-12">
                <h2>Jodi Play</h2>
              </div>
            </div>

          </div>
          <div class="row">
            <div class="game">
              <div class="col-lg-12 col-md-12 col-sm-12">
                <h2>Crossing</h2>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="game">
              <div class="col-lg-12 col-md-12 col-sm-12">
                <h2>From-to</h2>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="game">
              <div class="col-lg-12 col-md-12 col-sm-12">
                <h2>ander-bahar haruf</h2>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer justify-content-center">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

        </div>
      </div>
    </div>
  </div>
    <!-- jQuery -->
<script src="{{ asset('game/assets/js/jquery-3.6.0.min.js') }}"></script>
<!-- Bootstrap Core JS -->
<script src="{{ asset('game/assets/js/popper.min.js') }}"></script>
<script src="{{ asset('game/assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Slimscroll JS -->
<script src="{{ asset('game/assets/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- Select2 JS -->
<script src="{{ asset('game/assets/js/select2.min.js') }}"></script>
<!-- Custom JS -->
<script src="{{ asset('game/assets/js/admin.js') }}"></script>
<!-- jquery-validation -->
<script src="{{ asset('plugins/jquery-validation/jquery.validate.min.js') }}"></script>
<script src="{{ asset('plugins/jquery-validation/additional-methods.min.js') }}"></script>

<script src="{{ asset('assets/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.timepicker.min.js') }}"></script>
<script src="{{ asset('assets/js/timepicker.min.js') }}"></script>
<script>
      //Handle Input table only accept numeric value
     $(document).on('keypress keyup input dragover drop','.account_number',function(e){
          return e.charCode >= 48 && e.charCode <= 57 && this.value.length<20;
      });
</script>

</body>
</html>

resources/views/admin/bank-account/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0" />
  <title>Account Number</title>

<!-- Favicons -->
<link rel="shortcut icon" href="{{ asset('game/assets/img/favicon.png') }}">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{{ asset('game/assets/plugins/bootstrap/css/bootstrap.min.css') }}">

<!-- Fontawesome CSS -->
<link rel="stylesheet" href="{{ asset('game/assets/plugins/fontawesome/css/fontawesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('game/assets/plugins/fontawesome/css/all.min.css') }}">

<!-- Animate CSS -->
<link rel="stylesheet" href="{{ asset('game/assets/css/animate.min.css') }}">

<!-- Main CSS -->
<!-- <link rel="stylesheet" href="{{ asset('game/assets/css/admin.css') }}"> -->
<link rel="stylesheet" href="{{ asset('game/assets/css/admin1.css') }}">
	<!-- Datatables CSS -->
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
</head>

<body>
  <div class="main-wrapper">
    <div class="header">
      <div class="header-left">
      </div>
       <a href="javascript:void(0);" id="toggle_btn">
         <i class="fas fa-align-left"></i>
      </a>
      <a class="mobile_btn" id="mobile_btn" href="javascript:void(0);">
         <i class="fas fa-align-left"></i>
      </a>
      <h3>Account Number</h3>
      <ul class="nav user-menu">
        <li class="nav-item dropdown noti-dropdown">
          <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
          </a>
        </li>
        <li class="nav-item dropdown">
          <a href="javascript:void(0)" class="dropdown-toggle user-link nav-link" data-bs-toggle="dropdown">
            <h4>Profile</h4>
          </a>
        </li>

      </ul>
    </div>
    <!-- /Header -->
    @switch(true)
        @case(Auth::user()->hasRole('User'))
            @include('layouts.user_game.sidebar')
            @include('layouts.user_game.flash_msg')
            @break
        @case(Auth::user()->hasRole('Agent'))
            @include('layouts.agent.sidebar')
            @include('layouts.agent.flash_msg')
            @break
        @case(Auth::user()->hasRole('Partner'))
            @include('layouts.partner.sidebar')
            @include('layouts.partner.flash_msg')
    @endswitch
    <div class="page-wrapper">

      <div class="content container-fluid">
        
        <div class="row pricing-box">
          <div class="row col align-self-end">
            <!-- <div class="col-md-6">
            </div> -->
            <div class="col-md-2 offset-md-11">
            <a href="{{ route('bank-accounts.create') }}" type="button" class="btn btn-success bg-info" title="edit">Add Bank</a>
            </div>
          </div>
          <div class="col-xl-12">
            <div class="row">
            <div class="col-md-12">
						<div class="card">
                <div class="card-body">
								<div class="table-responsive" add-account="{{ route('bank-accounts.create') }}">
									<table class="table table-hover table-center mb-0" id="tbl_user_history">
										<thead>
											<tr>
												<th>#</th>
												<th>A/C Holder Name</th>
												<th>A/C Number</th>
												<th>IFSC Code</th>
												<th>Action</th>
											</tr>
										</thead>
										<tbody>
                    @foreach($data as $k => $v)
                    <tr>
                    <td>{{++$k}}</td>
                    <td>{{ $v->account_holder_name ? $v->account_holder_name : ''}}</td>
                    <td>{{ $v->account_number ? $v->account_number : ''}}</td>
                    <td>{{ $v->ifsc_code ? $v->ifsc_code : ''}}</td>
                      <td><a href="{{ route('bank-accounts.edit',$v->id) }}" type="button" class="" style="display:inline" title="edit"><i class="fa fa-edit"></i></a>
                      <form action="{{ route('bank-accounts.destroy',$v->id) }}" method="post" style="display:inline;" onsubmit=" return confirm('Are you sure ?')">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="float-left"><i class="fa fa-trash" title="delete"></i></button></td>
                      </form>
											</tr>
                        @endforeach
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>

            </div>

          </div>


        </div>

      </div>
    </div>
  </div>
  <div class="modal fade" id="staticBackdrop4" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel4" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header justify-content-center">
          <h2 class="modal-title" id="staticBackdropLabel4">Choise</h2>

        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-lg-6 ">
              <div class="col-lg-6 repeattt">
                <table style="width:100% ">
                </table>
                <div class="row repeat-secc">
                  <div class="col-lg-12 col-sm-12 col-md-12">
                    <div class="row">
                      <div class="col-lg-6">
                        <div class="price">
                          <i class="fas fa-rupee-sign"></i>
                        </div>
                      </div>
                      <div class="col-lg-6">
                        <div class="today-btn">
                          <a href="javascript:void(0)"> Total Aount </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer justify-content-center">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
    <!-- jQuery -->
<script src="{{ asset('game/assets/js/jquery-3.6.0.min.js') }}"></script>
<!-- Datatables JS -->
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
<!-- Bootstrap Core JS -->
<script src="{{ asset('game/assets/js/popper.min.js') }}"></script>
<script src="{{ asset('game/assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Slimscroll JS -->
<script src="{{ asset('game/assets/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- Select2 JS -->
<script src="{{ asset('game/assets/js/select2.min.js') }}"></script>
<!-- Custom JS -->
<script src="{{ asset('game/assets/js/admin.js') }}"></script>
<script>
  $(document).ready(function() { 
    $('#tbl_user_history').DataTable();  
  });
</script>
</body>
</html>