routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\{UserController,BankAccountController,wallethistoryController};
use App\Http\Controllers\Admin\{AnalystController, AccountController, WalletController, AgentController, QuestionsController, AnswersController, CallLogController, AnalystProfileController, AnalystBannerController, VideosController, BannerController, ContestController, UserContestController, UserKycController, PostController,  UserGameController, PartnerController };

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::get('/terms', function () {
    return view('terms');
});



Auth::routes();

Route::get('/logcheck', [App\Http\Controllers\HomeController::class, 'logcheck']);
Route::post('/admin-login', [App\Http\Controllers\HomeController::class, 'logincheck'])->name('admin-login');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/otp-verification', [App\Http\Controllers\Auth\LoginController::class, 'checkOtp'])->name('checkOtp');
Route::post('/otp-verify', [App\Http\Controllers\Auth\LoginController::class, 'verifyOtp'])->name('verify-otp');
Route::get('/gms', [App\Http\Controllers\HomeController::class, 'testing']);
Route::get('/live', function () {
    return view('live');
});

Route::post('register',[UserController::class, 'register'])->name('user.register');

   //Start User Game play Route Here
   Route::group(['middleware' => ['auth', 'checkRole:User']], function () {
    Route::resource('user-game', UserGameController::class);
    Route::get('game/choose-game',[UserGameController::class, 'GameTypeView'])->name('GameTypeView');
    Route::get('game/game-history',[UserGameController::class, 'GameHistory'])->name('GameHistory');
    Route::get('game/wallet-history',[UserGameController::class, 'WalletHistory'])->name('WalletHistory');
    Route::post('game/addBallanceWallet',[UserGameController::class, 'addBallanceWallet'])->name('addBallanceWallet');
    Route::get('game/list',[UserGameController::class, 'GameList'])->name('GameList');
    Route::any('user/{id?}/play-game/{game_type?}',[UserGameController::class, 'playGameView'])->name('user.playGame');
    Route::post('user/play-gameStore',[UserGameController::class, 'playGameStore'])->name('user.playGame.store');
    Route::get('user/play-game/history',[UserGameController::class, 'playGameHistory'])->name('user.playGame.history');
    Route::get('user/play-game/dashboard/{id?}',[UserGameController::class, 'playGameDashboard'])->name('user.playGame.dashboard');

    Route::get('user/previous-game',[UserGameController::class, 'previousGame'])->name('user.previousGame');
});
//End User Game play Route Here

  //Start Partner Dashboard Route Here
  Route::group(['middleware' => ['auth', 'checkRole:Partner'], 'prefix' => 'partner'], function () {
    Route::get('dashboard', [PartnerController::class,'index'])->name('partner.dashboard');
    Route::get('game/create-game',[PartnerController::class, 'GameCreateView'])->name('partner.GameCreateView');
     Route::post('game/create-game',[PartnerController::class, 'GameCreateStore'])->name('partner.GameCreateStore');
    Route::get('game/game-history',[PartnerController::class, 'GameHistory'])->name('partner.GameHistory');
    Route::get('game/{id?}/settings',[PartnerController::class, 'GameSettings'])->name('partner.GameSettings');
    Route::get('/game',[PartnerController::class, 'DataFetch'])->name('partner.DataFetch');

});
//End Partner Dashboard Route Here


 //Start Agent Dashboard Route Here
 Route::group(['middleware' => ['auth', 'checkRole:Agent'], 'prefix' => 'agent'], function () {
     Route::get('dashboard', [AgentController::class,'index'])->name('agent.dashboard');
     Route::get('game/create-user',[AgentController::class, 'UserCreateView'])->name('agent.UserCreateView');
     Route::post('game/create-user',[AgentController::class, 'UserCreateStore'])->name('agent.UserCreateStore');
     Route::get('game/edit-user/{user_id?}',[AgentController::class, 'UserEditView'])->name('agent.UserEditView');
     Route::post('game/edit-user/{user_id?}',[AgentController::class, 'UserEditStore'])->name('agent.UserEditStore');
     Route::get('game/user-history',[AgentController::class, 'UserHistory'])->name('agent.UserHistory');
     Route::post('game/delete-user/{user_id?}',[AgentController::class, 'UserDestroy'])->name('agent.UserDestroy');
});
//End Agent Dashboard Route Here

Route::group(['middleware' => ['auth', 'checkRole:Admin']], function () {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('analysts', AnalystController::class);
    Route::resource('videos', VideosController::class);
    Route::resource('contest', ContestController::class);
    Route::get('contest/uploda-result/{id?}', [ContestController::class, 'ContestUploadResult'])->name('contest.upload.result');
    Route::post('contest/uploda-result/{id?}', [ContestController::class, 'ContestUploadResultStore'])->name('contest.upload.result.store');
    Route::get('contest/aproved/{id?}', [ContestController::class, 'approveContest'])->name('contest.aproved');
    Route::get('prize/distribution', [ContestController::class, 'prizeDistribution'])->name('contest.prizedistribution');
    Route::get('prize/{id?}', [ContestController::class, 'prizeDistributionView'])->name('contest.prize');

    Route::get('contest-answer', [ContestController::class, 'contestAnswer'])->name('contest.answer');
    Route::get('contest-answer-edit/{id?}', [ContestController::class, 'editAnswer'])->name('contest.editanswer');
    Route::post('contest-answer-save/{id?}', [ContestController::class, 'saveContestAns'])->name('contest.editanswersave');
    Route::resource('user_contest', UserContestController::class);
    Route::resource('wallets', WalletController::class);
    Route::resource('user_kyc', UserKycController::class);
    Route::resource('post', PostController::class);
    Route::get('wallets/{wallet}', [WalletController::class, 'show'])->name('wallets.show');

    Route::get('videos/aproved/{id?}', [VideosController::class, 'approveVideos'])->name('videos.aproved');
    Route::get('analysts/aproved/{id?}', [AnalystController::class, 'approveAnalyst'])->name('analysts.aproved');
    Route::get('analyst/account', [AccountController::class, 'index'])->name('account.index');
    Route::get('notification', [ContestController::class, 'notificationView'])->name('notification.create');
    Route::get('notification-list', [ContestController::class, 'notificationList'])->name('notification.index');
    Route::get('leader-board', [ContestController::class, 'leaderBoardList'])->name('leaderboard');
    Route::get('winners', [ContestController::class, 'winnerList'])->name('winnerlist');
    //Start User Management Route Here
    //Route::resource('products', ProductController::class);
    Route::resource('questions', QuestionsController::class);
    Route::resource('answers', AnswersController::class);
    Route::resource('call-logs', CallLogController::class);
    Route::resource('profiles', AnalystProfileController::class);
    Route::resource('banners', AnalystBannerController::class);
    Route::resource('banner', BannerController::class);

});

//Start some common group route here
Route::group(['middleware' => ['auth', 'checkRole:User,Partner,Agent']], function () {
    Route::resource('bank-accounts', BankAccountController::class);
});


//End some common group route here

Route::get('matka/test', [VideosController::class, 'matkaTest']);
Route::get('base64ToString', [UserController::class, 'decodeBase64']);

app/Models/Contest.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contest extends Model
{
    use HasFactory, SoftDeletes;
    protected $table = 'contests';
    protected $guarded = [];

    public function getContestData()
    {
        return $this->hasMany(ContestData::class);
    }
}

resources/views/admin/contest/create.blade.php
@extends('layouts.app_new')
@section('title','Matka || Create Game')
@section('header_title','Create Game')
@push('css')
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/bootstrap-datepicker.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/jquery.timepicker.css')}}"/>
@endpush
@section('content')
 <!-- Main content -->
 <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            @if ( Session::has('success'))
            <div class="alert alert-success" role="alert" id="alert_msg">
                {{ Session::get('success') }}
            </div> 
            @endif
             @if ( Session::has('danger'))
            <div class="alert alert-danger" role="alert" id="alert_msg">
                {{ Session::get('danger') }}
            </div> 
            @endif
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <!-- <h3 class="card-title">Create <small>User</small></h3> -->
                <a href="{{ route('contest.index') }}" type="button" class="btn btn-info">Back</a>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="frm_contest_save" method="post" action="{{ route('contest.store') }}" enctype="multipart/form-data">
                @csrf
                <!-- /.card-header -->
                  <div class="card-body">
                      <div class="row">
                       <div class="col-12 col-sm-12">
                        <div class="form-group">
                        <label for="exampleInputEmail1">Game Name</label>
                        <input type="text" name="contest_name" class="form-control" id="contest_name" placeholder="Enter Game Name" value="{{old('contest_name')}}" required>
                        @error('contest_name')
                          <li style="color:#e71814">{{ $message }}</li>
                        @enderror
                        </div>
                      </div>
                    </div>
                      
                    <!-- <div class="row">
                      <div class="col-12 col-sm-6">
                        <div class="form-group">
                        <label>Start Date</label> 
                        <input type="text" name="start_date" class="form-control" id="start_date" placeholder="Enter Start Date" value="{{old('start_date')}}" required readonly>
                        @error('start_date')
                          <li style="color:#e71814">{{ $message }}</li>
                        @enderror
                        </div>
                      </div>

                      <div class="col-12 col-sm-6"> 
                        <div class="form-group">
                        <label for="exampleInputEmail1">End Date</label>
                            <input type="text" name="end_date" class="form-control" id="end_date" placeholder="Enter End Date" value="{{old('end_date')}}" required readonly>
                        @error('end_date')
                          <li style="color:#e71814">{{ $message }}</li>
                        @enderror
                        </div>
                      </div>
                      </div> -->

                      <div class="row">
                      <div class="col-12 col-sm-6">
                        <div class="form-group">
                        <label for="exampleInputMobile">Start Time</label>
                        <input type="text" name="start_time" class="form-control" id="start_time" placeholder="Enter Start Time" value="{{old('start_time')}}" required >
                        @error('start_time')
                          <li style="color:#e71814">{{ $message }}</li>
                        @enderror
                        </div>
                      </div>
                      <div class="col-12 col-sm-6"> 
                        <div class="form-group">
                        <label for="exampleInputPassword1">End Time</label>
                        <input type="text" name="end_time" class="form-control" id="end_time" placeholder="Enter End Time" value="{{old('end_time')}}" required >
                          @error('end_time')
                          <li style="color:#e71814">{{ $message }}</li>
                          @enderror
                        </div> 
                      </div>
                    </div>
                    <!-- /.row -->

                    <div class="row">
                        <div class="col-12 col-sm-12">
                          <label for="formFile" class="form-label">Description</label>
                          <textarea id="description" class="form-control" name="description" Placeholder=" Enter Description" required>{{old('description')}}</textarea>
                          @error('description')
                          <li style="color:#e71814">{{ $message }}</li>
                          @enderror
                        </div>
                    </div>

                    <div class="row">
                        <!-- <div class="col-12 col-sm-6">
                          <label for="formFile" class="form-label">Member Logo</label>
                          <input class="form-control" type="file" id="member_logo" name="member_logo" placeholder="Choose Logo">
                          @error('member_logo')
                          <li style="color:#e71814">{{ $message }}</li>
                          @enderror 
                          <br><img style="width:10%" id="memberLogoPreview" src="" alt="profile photo" class="" onerror="this.onerror=null;this.src='{{asset('members_image/avatar_male.png')}}';">
                        </div> -->

                        <div class="col-12 col-sm-6">
                          <label for="formFile" class="form-label">Game Image</label>
                          <input class="form-control" type="file" id="contest_image" name="contest_image" placeholder="Choose Contest Image">
                          @error('contest_image')
                          <li style="color:#e71814">{{ $message }}</li>
                          @enderror
                          <br><img style="width:10%" id="contestImagePreview" src="" alt="profile photo" class="" onerror="this.onerror=null;this.src='{{asset('members_image/avatar_male.png')}}';">
                        </div>  
                    </div>

                  </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@push('scripts')
<!-- jquery-validation -->
<script src="{{ asset('plugins/jquery-validation/jquery.validate.min.js') }}"></script>
<script src="{{ asset('plugins/jquery-validation/additional-methods.min.js') }}"></script>

<script src="{{ asset('assets/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.timepicker.min.js') }}"></script>
<script src="{{ asset('assets/js/timepicker.min.js') }}"></script>

<!-- Page specific script -->
<script>
  //alert()
      //TIMEPICKER
        $('#start_time, #end_time').timepicker({
        'timeFormat': 'H:i', // Use 'H' for 24-hour format without AM/PM
        'step': 30,
        'scrollDefault': 'now'
      });

// Event handler for start time change
$('#start_time').on('changeTime', function() {
    var startTime = $('#start_time').val();
    var endTime = $('#end_time').val();

    // Check if end time is the same or less than start time
    if (endTime <= startTime) {
      // Set end time to a minute after start time
      var newEndTime = new Date($('#start_time').timepicker('getTime'));
      newEndTime.setMinutes(newEndTime.getMinutes() + 1);
      $('#end_time').timepicker('setTime', newEndTime);
    }
  });

  // Event handler for end time change
  $('#end_time').on('changeTime', function() {
    var startTime = $('#start_time').val();
    var endTime = $('#end_time').val();

    // Check if end time is the same or less than start time
    if (endTime <= startTime) {
      // Set start time to a minute before end time
      var newStartTime = new Date($('#end_time').timepicker('getTime'));
      newStartTime.setMinutes(newStartTime.getMinutes() - 1);
      $('#start_time').timepicker('setTime', newStartTime);
    }
  });


  $("#start_date").datepicker({
    format: 'dd M yyyy',
    autoclose: true,
    immediateUpdates: true,
    todayBtn: 'linked',
    todayHighlight: true,
    startDate: new Date()
}).on('changeDate', function (selected) {
    var minDate = new Date(selected.date.valueOf());
    $('#end_date').datepicker('setStartDate', minDate);
});

$("#end_date").datepicker({
    format: 'dd M yyyy',
    autoclose: true,
    immediateUpdates: true,
    todayBtn: 'linked',
    todayHighlight: true,
    startDate: new Date()
}).on('changeDate', function (selected) {
    var maxDate = new Date(selected.date.valueOf());
    $('#start_date').datepicker('setEndDate', maxDate);
});


  $('#member_logo').change(function(){
        const file = this.files[0];
        if (file){
          let reader = new FileReader();
          reader.onload = function(event){
            //console.log(event.target.result);
            $('#memberLogoPreview').attr('src', event.target.result);
          }
          reader.readAsDataURL(file);
        }
      });
      $('#contest_image').change(function(){
        const file = this.files[0];
        if (file){
          let reader = new FileReader();
          reader.onload = function(event){
            //console.log(event.target.result);
            $('#contestImagePreview').attr('src', event.target.result);
          }
          reader.readAsDataURL(file);
        }
      });
    $(document).ready(function(){
    //Initialize Select2 Elements
    $('.select2').select2();
    });

$(function () {
//   $.validator.setDefaults({
//     submitHandler: function () {
//       alert( "Form successful submitted!" );
//     }
//   });
  $('#frm_contest_save').validate({
    rules: {
      name: {
        required: true,
      },
      mobile: {
        required: true,
        minlength: 10,
        maxlength: 10,
      },
      email: {
        required: true,
        email: true,
      },
      password: {
        required: true,
        minlength: 5
      },
      terms: {
        required: true
      },
    },
    messages: {
        name: {
        required: "Please enter name",
      },
      mobile: {
        required: "Please enter Mobile",
        minlength: "Your mobile must be at least 10 digit",
        maxlength: "Your mobile must be at equal 10 digit"
      },
      email: {
        required: "Please enter a email address",
        email: "Please enter a valid email address"
      },
      password: {
        required: "Please provide a password",
        minlength: "Your password must be at least 5 characters long"
      },
      terms: "Please accept our terms"
    },
    errorElement: 'span',
    errorPlacement: function (error, element) {
      error.addClass('invalid-feedback');
      element.closest('.form-group').append(error);
    },
    highlight: function (element, errorClass, validClass) {
      $(element).addClass('is-invalid');
    },
    unhighlight: function (element, errorClass, validClass) {
      $(element).removeClass('is-invalid');
    }
  });
});
</script>
@endpush

resources/views/admin/contest/index.blade.php
@extends('layouts.app_new')
@section('title','Matka || Game Management')
@section('header_title','Game')
@push('css')
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/bootstrap-datepicker.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/jquery.timepicker.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/daterangepicker.css')}}"/>
@endpush
@section('content')
<!-- Main content -->
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- /.card -->
            @if ( Session::has('success'))
            <div class="alert alert-success" role="alert" id="alert_msg">
                {{ Session::get('success') }}
            </div> 
            @endif
             @if ( Session::has('danger'))
            <div class="alert alert-danger" role="alert" id="alert_msg">
                {{ Session::get('danger') }}
            </div> 
            @endif
            <div class="card">
              <div class="card-header">
              <div class="row">
                  <div class="col-md-4">
                    <div id="datepicker" class="form-control" style="background: #fff; cursor: pointer; border: 1px solid #ccc;">
                      <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
                      <span></span> <b class="caret"></b>
                      </div>
                      <div class="col-md-4"></div>
                      <div class="col-md-4"></div>
                  </div>
                </div>
                <!-- <h3 class="card-title">Contest</h3> -->
                @can('product-create')
                <a href="{{ route('contest.create') }}" type="button" class="btn btn-info float-right">Create New Game</a>
                @endcan
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="tbl_contest_list" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>#</th>
                    <th>Game Name</th>
                    <!-- <th>Game Time</th> -->
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Description</th>
                    <th>Created By</th>
                    <th>Approval</th>
                    <!-- <th>Answer</th> -->
                    <!-- <th>Prize</th> -->
                    <th>Action</th>
                    <th>Upload Result</th>
                  </tr>
                  </thead>
                  <tbody>
                  @foreach($data as $k => $v)  
                  <tr>
                    <td>{{++$k}}</td>
                    <td>{{$v->contest_name ? $v->contest_name : ''}}</td>
                    <!-- <td>{{$v->contest_time ? $v->contest_time : ''}}</td> -->
                    <td><label class="badge badge-success">{{$v->start_end_time ? date(TIME_FORMAT_AM_PM,strtotime($v->start_end_time)) : ''}}</label></td>
                    <td><label class="badge badge-success">{{$v->end_time ? date(TIME_FORMAT_AM_PM,strtotime($v->end_time)) : ''}}</label></td>
                    <td>{{$v->description ?  \Illuminate\Support\Str::limit($v->description, 70, $end='...') : ''}}</td>
                    <td>{{$v->creater_name ? $v->creater_name : ''}}&nbsp;({{$v->creater_email ? $v->creater_email : ''}})</td>
                    <td>
                      @if($v->status == 1)
                      <a href="{{ route('contest.aproved', $v->id) }}" onclick="return confirm('Are You Sure Want to do Pending ?')" type="button" class="btn btn-success">Approved</a>
                      @else
                      <a href="{{ route('contest.aproved', $v->id) }}" onclick="return confirm('Are You Sure Want to do Approved ?')" type="button" class="btn btn-warning">Pending</a>
                      @endif
                    </td>
                    <!-- <td>
                    <a href="{{ route('contest.editanswer',$v->cr_id) }}" type="button" class="btn btn-primary float-left" style="display:inline"><i class="fa fa-check" aria-hidden="true"></i></a>
                    </td> -->
                    <!-- <td>
                    <a href="{{ route('contest.prize',$v->id) }}" type="button" class="btn btn-warning float-left" style="display:inline"><i class="fa fa-trophy" aria-hidden="true"></i></a>
                    </td> -->
                    <td>
                    @can('product-edit') 
                      <a href="{{ route('contest.edit',$v->id) }}" type="button" class="btn btn-primary float-left" style="display:inline"><i class="fa fa-edit"></i></a>
                    @endcan
                    @can('product-delete')
                      <button type="submit"  class="btn btn-danger" style="display:inline"><i class="fa fa-trash"></i></button>
                    @endcan
                    </td>
                   <td>
                   <a href="{{ route('contest.upload.result', $v->id) }}" type="button" class="btn btn-primary">Upload</a>
                   </td>
                  </tr>
                  @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- Modal -->
@endsection

@push('scripts')
<script src="{{ asset('assets/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.timepicker.min.js') }}"></script>
<script src="{{ asset('assets/js/timepicker.min.js') }}"></script>
<script src="{{ asset('assets/js/daterangepicker.js') }}"></script>
<script>
$(document).ready(function() {
    //cb(moment().startOf('month'), moment().endOf('month'));
    $('#datepicker').daterangepicker({
        startDate: moment().startOf('month'),
        endDate: moment().endOf('month'),
        ranges: {
            'Today': [moment(), moment()],
            'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Last 7 Days': [moment().subtract(6, 'days'), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month till Date': [moment().startOf('month'), moment()],
            'Year till Date': [moment().startOf('year'), moment()],
            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
            'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
            'Last Year': [moment().subtract(1, 'year').startOf('year'), moment().subtract(1, 'day').startOf('year')]

        }
    }, cb);


// Attach the event listener for when the apply button is clicked
$('#datepicker').on('apply.daterangepicker', function (ev, picker) {
  document.getElementById('spinner-overlay').style.display = 'block';
    var fromDate = moment(picker.startDate).format('YYYY-MM-DD');
    var toDate = moment(picker.endDate).format('YYYY-MM-DD')
    const url = `{{route('contest.index') }}?fromDate=${fromDate}&toDate=${toDate}`;
    window.location.href = url;
  });

function getDatesFromUrl() {
        const urlParams = new URLSearchParams(window.location.search);
        const fromDate = urlParams.get('fromDate');
        const toDate = urlParams.get('toDate');
        
        return {
            start: fromDate ? moment(fromDate) : moment().startOf('month'),
            end: toDate ? moment(toDate) : moment()
        };
    }

    // Initial call to set the dates from URL parameters
    const initialDates = getDatesFromUrl();
    //console.log(initialDates.start.format('YYYY-MM-DD'))
    cb(initialDates.start, initialDates.end);

function cb(start, end) {
  $('#datepicker span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
}


  $(function () {
    $("#tbl_contest_list").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
    //   "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      "buttons": ["csv", "excel"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
  });
</script>
@endpush