routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\{UserController,BankAccountController,wallethistoryController};
use App\Http\Controllers\Admin\{AnalystController, AccountController, WalletController, AgentController, QuestionsController, AnswersController, CallLogController, AnalystProfileController, AnalystBannerController, VideosController, BannerController, ContestController, UserContestController, UserKycController, PostController,  UserGameController, PartnerController };

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::get('/terms', function () {
    return view('terms');
});



Auth::routes();

Route::get('/logcheck', [App\Http\Controllers\HomeController::class, 'logcheck']);
Route::post('/admin-login', [App\Http\Controllers\HomeController::class, 'logincheck'])->name('admin-login');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/otp-verification', [App\Http\Controllers\Auth\LoginController::class, 'checkOtp'])->name('checkOtp');
Route::post('/otp-verify', [App\Http\Controllers\Auth\LoginController::class, 'verifyOtp'])->name('verify-otp');
Route::get('/gms', [App\Http\Controllers\HomeController::class, 'testing']);
Route::get('/live', function () {
    return view('live');
});

Route::post('register',[UserController::class, 'register'])->name('user.register');

   //Start User Game play Route Here
   Route::group(['middleware' => ['auth', 'checkRole:User']], function () {
    Route::resource('user-game', UserGameController::class);
    Route::get('game/choose-game',[UserGameController::class, 'GameTypeView'])->name('GameTypeView');
    Route::get('game/game-history',[UserGameController::class, 'GameHistory'])->name('GameHistory');
    Route::get('game/wallet-history',[UserGameController::class, 'WalletHistory'])->name('WalletHistory');
    Route::post('game/addBallanceWallet',[UserGameController::class, 'addBallanceWallet'])->name('addBallanceWallet');
    Route::get('game/list',[UserGameController::class, 'GameList'])->name('GameList');
    Route::any('user/{id?}/play-game/{game_type?}',[UserGameController::class, 'playGameView'])->name('user.playGame');
    Route::post('user/play-gameStore',[UserGameController::class, 'playGameStore'])->name('user.playGame.store');
    Route::get('user/play-game/history',[UserGameController::class, 'playGameHistory'])->name('user.playGame.history');
    Route::get('user/play-game/dashboard/{id?}',[UserGameController::class, 'playGameDashboard'])->name('user.playGame.dashboard');

    Route::get('user/previous-game',[UserGameController::class, 'previousGame'])->name('user.previousGame');
});
//End User Game play Route Here

  //Start Partner Dashboard Route Here
  Route::group(['middleware' => ['auth', 'checkRole:Partner'], 'prefix' => 'partner'], function () {
    Route::get('dashboard', [PartnerController::class,'index'])->name('partner.dashboard');
    Route::get('game/create-game',[PartnerController::class, 'GameCreateView'])->name('partner.GameCreateView');
     Route::post('game/create-game',[PartnerController::class, 'GameCreateStore'])->name('partner.GameCreateStore');
    Route::get('game/game-history',[PartnerController::class, 'GameHistory'])->name('partner.GameHistory');
    Route::get('game/{id?}/settings',[PartnerController::class, 'GameSettings'])->name('partner.GameSettings');
    Route::get('/game',[PartnerController::class, 'DataFetch'])->name('partner.DataFetch');

});
//End Partner Dashboard Route Here


 //Start Agent Dashboard Route Here
 Route::group(['middleware' => ['auth', 'checkRole:Agent'], 'prefix' => 'agent'], function () {
     Route::get('dashboard', [AgentController::class,'index'])->name('agent.dashboard');
     Route::get('game/create-user',[AgentController::class, 'UserCreateView'])->name('agent.UserCreateView');
     Route::post('game/create-user',[AgentController::class, 'UserCreateStore'])->name('agent.UserCreateStore');
     Route::get('game/edit-user/{user_id?}',[AgentController::class, 'UserEditView'])->name('agent.UserEditView');
     Route::post('game/edit-user/{user_id?}',[AgentController::class, 'UserEditStore'])->name('agent.UserEditStore');
     Route::get('game/user-history',[AgentController::class, 'UserHistory'])->name('agent.UserHistory');
     Route::post('game/delete-user/{user_id?}',[AgentController::class, 'UserDestroy'])->name('agent.UserDestroy');
});
//End Agent Dashboard Route Here

Route::group(['middleware' => ['auth', 'checkRole:Admin']], function () {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('analysts', AnalystController::class);
    Route::resource('videos', VideosController::class);
    Route::resource('contest', ContestController::class);
    Route::get('contest/uploda-result/{id?}', [ContestController::class, 'ContestUploadResult'])->name('contest.upload.result');
    Route::post('contest/uploda-result/{id?}', [ContestController::class, 'ContestUploadResultStore'])->name('contest.upload.result.store');
    Route::get('contest/aproved/{id?}', [ContestController::class, 'approveContest'])->name('contest.aproved');
    Route::get('prize/distribution', [ContestController::class, 'prizeDistribution'])->name('contest.prizedistribution');
    Route::get('prize/{id?}', [ContestController::class, 'prizeDistributionView'])->name('contest.prize');

    Route::get('contest-answer', [ContestController::class, 'contestAnswer'])->name('contest.answer');
    Route::get('contest-answer-edit/{id?}', [ContestController::class, 'editAnswer'])->name('contest.editanswer');
    Route::post('contest-answer-save/{id?}', [ContestController::class, 'saveContestAns'])->name('contest.editanswersave');
    Route::resource('user_contest', UserContestController::class);
    Route::resource('wallets', WalletController::class);
    Route::resource('user_kyc', UserKycController::class);
    Route::resource('post', PostController::class);
    Route::get('wallets/{wallet}', [WalletController::class, 'show'])->name('wallets.show');

    Route::get('videos/aproved/{id?}', [VideosController::class, 'approveVideos'])->name('videos.aproved');
    Route::get('analysts/aproved/{id?}', [AnalystController::class, 'approveAnalyst'])->name('analysts.aproved');
    Route::get('analyst/account', [AccountController::class, 'index'])->name('account.index');
    Route::get('notification', [ContestController::class, 'notificationView'])->name('notification.create');
    Route::get('notification-list', [ContestController::class, 'notificationList'])->name('notification.index');
    Route::get('leader-board', [ContestController::class, 'leaderBoardList'])->name('leaderboard');
    Route::get('winners', [ContestController::class, 'winnerList'])->name('winnerlist');
    //Start User Management Route Here
    //Route::resource('products', ProductController::class);
    Route::resource('questions', QuestionsController::class);
    Route::resource('answers', AnswersController::class);
    Route::resource('call-logs', CallLogController::class);
    Route::resource('profiles', AnalystProfileController::class);
    Route::resource('banners', AnalystBannerController::class);
    Route::resource('banner', BannerController::class);

});

//Start some common group route here
Route::group(['middleware' => ['auth', 'checkRole:User,Partner,Agent']], function () {
    Route::resource('bank-accounts', BankAccountController::class);
});


//End some common group route here

Route::get('matka/test', [VideosController::class, 'matkaTest']);
Route::get('base64ToString', [UserController::class, 'decodeBase64']);

app/Models/banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class banner extends Model
{
    use HasFactory, SoftDeletes;
    protected $table = 'banners';
    protected $guarded = [];
}

app/Http/Controllers/Admin/AnalystController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\UserDetail;
use Spatie\Permission\Models\Role;
use DB;
use Hash;
use File;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class AnalystController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $data = User::role('Analyst')->with('userdetails')->orderBy('users.id','DESC')->get();
        return view('admin.analyst.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::select('name')->get();
        return view('admin.analyst.create',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'mobile' => 'required|unique:users',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);
    
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
    
        $user = User::create($input);
        $channal_name = (string) Str::uuid();
            UserDetail::create([
                'user_id' => $user->id,
                'channal_name' => $channal_name,
            ]);
        $user->assignRole($request->input('roles'));
    
        return back()->with('success','Analyst created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        //return view('admin.analyst.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //$user = User::find($id);
        $user = User::with('userdetails')->find($id);
        $roles = Role::select('name')->get();
        $userRole = $user->roles->pluck('name','name')->all();
        $languages = DB::table('languages')->select('id','name','code')->get();
        return view('admin.analyst.edit',compact('user','roles','userRole','languages'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($request->all());
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            'mobile' => 'required|unique:users,mobile,'.$id,
            //'password' => 'same:confirm-password',
            'roles' => 'required'
        ]);
    
        $input = $request->all();
        if(!empty($input['password'])){ 
            $input['password'] = Hash::make($input['password']);
        }else{
            $input = Arr::except($input,array('password'));    
        }
    
        $user = User::find($id);
        $user->update($input);
        $user_details = [
            'experience'                => $input['experience'] ? $input['experience'] : NULL,
            'consultant'                => $input['consultant'] ? $input['consultant'] : NULL,
            'language'                  => isset($input['language']) ? implode(',',$input['language']) : NULL,
            'location'                  => $input['location'] ? $input['location'] : NULL,
            'sebi'                      => $input['sebi'] ? $input['sebi'] : NULL,
            'bio'                       => $input['bio'] ? $input['bio'] : NULL,
            'description'               => $input['description'] ? $input['description'] : NULL,
            'voice_call_charges'        => $input['voice_call_charges'] ? $input['voice_call_charges'] : NULL,
            'video_call_charges'        => $input['video_call_charges'] ? $input['video_call_charges'] : NULL,
            'chat_call_charges'         => $input['chat_call_charges'] ? $input['chat_call_charges'] : NULL,
            'analyst_charges'           => $input['analyst_charges'] ? $input['analyst_charges'] : NULL,
            'live_stream_charges'           => $input['live_charges'] ? $input['live_charges'] : 0,
            'voice_call_enable'         => isset($input['voice_call_enable']) ? 1 : 0,
            'video_call_enable'         => isset($input['video_call_enable']) ? 1 : 0,
            'chat_call_enable'          => isset($input['chat_call_enable'])? 1 : 0,
            'updated_at'                => now(),
        ];
        //dd($user_details);
        if ($request->hasFile('profile')) {
            $file = $request->file('profile');
            $image = uniqid() . $file->getClientOriginalName();
            $path = 'members_image';
            $file->move($path, $image);
            $user_details['profile'] = $image;
            $exist_img = UserDetail::select('profile')->where('user_id', $id)->first();
            File::delete(public_path('members_image/' . $exist_img->profile));
        }
        UserDetail::where('user_id',$id)->update($user_details);
        DB::table('model_has_roles')->where('model_id',$id)->delete();
    
        $user->assignRole($request->input('roles'));
    
        return redirect()->route('analysts.index')
                        ->with('success','Analyst updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id){
        $query = User::find($id)->delete();
        if($query){
            return back()->with('danger','Analyst deleted successfully !');
        }
    }

    /**
     *Method for Approve Analyst.
     *
     * @return \Illuminate\Http\Response
     */   
    public function approveAnalyst(Request $request,$id){
        $user = User::with('userdetails')->find($id);
            if($user){
                $approved_status = ($user->userdetails['approved'] == 1) ? 0 : 1; 
                $approved_msg = ($user->userdetails['approved'] == 1) ? 'Pending' : 'Approved'; 
                UserDetail::where('user_id',$id)->update(['approved'=>$approved_status]);  
            }
        return back()->with('success',$approved_msg.' updated successfully');
    }
}

resources/views/admin/analyst/banners/create.blade.php
@extends('layouts.app_new')
@section('title','Analyst Ji || Create Banners')
@section('header_title','Create Banners')
@push('css')

@endpush
@section('content')
 <!-- Main content -->
 <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            @if ( Session::has('success'))
            <div class="alert alert-success" role="alert" id="alert_msg">
                {{ Session::get('success') }}
            </div> 
            @endif
             @if ( Session::has('danger'))
            <div class="alert alert-danger" role="alert" id="alert_msg">
                {{ Session::get('danger') }}
            </div> 
            @endif
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <!-- <h3 class="card-title">Create <small>User</small></h3> -->
                <a href="{{ route('banners.index') }}" type="button" class="btn btn-info">Back</a>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="frm_questions_save" method="post" action="{{ route('banners.store') }}" enctype="multipart/form-data">
                @csrf
                <!-- /.card-header -->
                  <div class="card-body">
                    <div class="row">
                      <div class="col-6 col-sm-6">
                        <div class="form-group">
                        <label for="banner">Banner</label>
                        <input class="form-control" type="file" id="banner_image" name="banner_image" placeholder="Choose Banner">
                        </div>
                      </div>
                      <div class="col-6 col-sm-4 offset-md-2">
                          <div class="form-group">
                            <div class="input-group">
                            <img style="height:100px;width:200px" id="imgPreview" src="" alt="profile photo" class="" onerror="this.onerror=null;this.src='{{asset('members_image/avatar-male.png')}}';">
                            </div>
                          </div>
                      </div>
                      <div class="col-12 col-sm-12">
                        <div class="form-group">
                        <label for="question">Status</label>
                        <select class="select2" name="status" style="width: 100%;">
                            <option value="1">Active</option>
                            <option value="0">Inactive</option>
                          </select>
                        </div>
                        <!-- /.form-group -->
                      </div>
                      <!-- /.col -->
                      
                        <!-- /.form-group -->
                      </div>
                      <!-- /.col -->

                    </div>
                    <!-- /.row -->
                    <div class="card-footer">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </div>
                
                <!-- /.card-body -->
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@push('scripts')
<!-- jquery-validation -->
<script src="{{ asset('plugins/jquery-validation/jquery.validate.min.js') }}"></script>
<script src="{{ asset('plugins/jquery-validation/additional-methods.min.js') }}"></script>

<!-- Page specific script -->
<script>
    $(document).ready(function(){
    //Initialize Select2 Elements
    $('.select2').select2();

    $('#banner_image').change(function(){
        const file = this.files[0];
        if (file){
          let reader = new FileReader();
          reader.onload = function(event){
            //console.log(event.target.result);
            $('#imgPreview').attr('src', event.target.result);
          }
          reader.readAsDataURL(file);
        }
      });

    });

$(function () {
//   $.validator.setDefaults({
//     submitHandler: function () {
//       alert( "Form successful submitted!" );
//     }
//   });
  $('#frm_questions_save').validate({
    rules: {
      question: {
        required: true,
      },
     
    },
    messages: {
        name: {
        required: "Please enter name",
      },
      mobile: {
        required: "Please enter Mobile",
        minlength: "Your mobile must be at least 10 digit",
        maxlength: "Your mobile must be at equal 10 digit"
      },
      email: {
        required: "Please enter a email address",
        email: "Please enter a valid email address"
      },
      password: {
        required: "Please provide a password",
        minlength: "Your password must be at least 5 characters long"
      },
      terms: "Please accept our terms"
    },
    errorElement: 'span',
    errorPlacement: function (error, element) {
      error.addClass('invalid-feedback');
      element.closest('.form-group').append(error);
    },
    highlight: function (element, errorClass, validClass) {
      $(element).addClass('is-invalid');
    },
    unhighlight: function (element, errorClass, validClass) {
      $(element).removeClass('is-invalid');
    }
  });
});
</script>
@endpush

resources/views/admin/analyst/banners/index.blade.php
@extends('layouts.app_new')
@section('title','Analyst Ji || Analyst Banners')
@section('header_title','Banners')
@section('content')
<!-- Main content -->
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- /.card -->
            @if ( Session::has('success'))
            <div class="alert alert-success" role="alert" id="alert_msg">
                {{ Session::get('success') }}
            </div> 
            @endif
             @if ( Session::has('danger'))
            <div class="alert alert-danger" role="alert" id="alert_msg">
                {{ Session::get('danger') }}
            </div> 
            @endif
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Banners</h3>
                @can('product-create')
                <a href="{{ route('banners.create') }}" type="button" class="btn btn-info float-right">Create New Banners</a>
                @endcan
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="tbl_usermanagement" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>#</th>
                    <th>Banner</th>
                    <th>Status</th>
                    @can('product-edit')
                    <th>Action</th>
                    @endcan
                  </tr>
                  </thead>
                  <tbody>
                  @foreach($data as $k => $v)  
                  <tr>
                    <td>{{++$k}}</td>
                    <td>
                    <img style="height:100px;width:200px" src="{{asset('banners_image')}}/{{$v->banner}}" alt="profile photo" class="" onerror="this.onerror=null;this.src='{{asset('members_image/avatar-male.png')}}';"></td>
                    <td>
                      <?php 
                      echo ($v->status == 1) ? '<button type="button"  class="btn btn-success">Active</button>' : '<button type="button"  class="btn btn-danger">Inactive</button>';
                      ?>
                    </td>
                    @can('product-edit')
                    <td>
                      <a href="{{ route('banners.edit',$v->id) }}" type="button" class="btn btn-primary float-left" style="display:inline;@cannot('product-edit')pointer-events:none; @endcannot ">Edit</a>
                    
                      <!-- <a href="javascript:void(0)" type="button" class="btn btn-primary">Edit</a> -->
                  
                      <!-- <a href="{{ route('users.show',$v->id) }}" type="button" class="btn btn-info">Show</a> -->
                
                    <form action="{{ route('banners.destroy', $v->id) }}" method="POST" style="display:inline;">
                      @csrf
                      @method('DELETE')
                      <button type="submit" onclick="return confirm('Are You Sure ?')" class="btn btn-danger" @cannot('product-delete') disabled @endcannot>Delete</button>
                  </form>
                  <!-- <button type="submit" onclick="return confirm('Are You Sure ?')" class="btn btn-danger" style="display:inline">Delete</button> -->
                  
                </td>
                @endcan
                  </tr>
                  @endforeach
                  </tbody>
                  <!-- <tfoot>
                  <tr>
                    <th>Rendering engine</th>
                    <th>Browser</th>
                    <th>Platform(s)</th>
                    <th>Engine version</th>
                    <th>CSS grade</th>
                  </tr>
                  </tfoot> -->
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@push('scripts')
<script>
  $(function () {
    $("#tbl_usermanagement").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
    //   "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      "buttons": ["csv", "excel"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
@endpush