routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\{UserController,BankAccountController,wallethistoryController};
use App\Http\Controllers\Admin\{AnalystController, AccountController, WalletController, AgentController, QuestionsController, AnswersController, CallLogController, AnalystProfileController, AnalystBannerController, VideosController, BannerController, ContestController, UserContestController, UserKycController, PostController,  UserGameController, PartnerController };

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::get('/terms', function () {
    return view('terms');
});



Auth::routes();

Route::get('/logcheck', [App\Http\Controllers\HomeController::class, 'logcheck']);
Route::post('/admin-login', [App\Http\Controllers\HomeController::class, 'logincheck'])->name('admin-login');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/otp-verification', [App\Http\Controllers\Auth\LoginController::class, 'checkOtp'])->name('checkOtp');
Route::post('/otp-verify', [App\Http\Controllers\Auth\LoginController::class, 'verifyOtp'])->name('verify-otp');
Route::get('/gms', [App\Http\Controllers\HomeController::class, 'testing']);
Route::get('/live', function () {
    return view('live');
});

Route::post('register',[UserController::class, 'register'])->name('user.register');

   //Start User Game play Route Here
   Route::group(['middleware' => ['auth', 'checkRole:User']], function () {
    Route::resource('user-game', UserGameController::class);
    Route::get('game/choose-game',[UserGameController::class, 'GameTypeView'])->name('GameTypeView');
    Route::get('game/game-history',[UserGameController::class, 'GameHistory'])->name('GameHistory');
    Route::get('game/wallet-history',[UserGameController::class, 'WalletHistory'])->name('WalletHistory');
    Route::post('game/addBallanceWallet',[UserGameController::class, 'addBallanceWallet'])->name('addBallanceWallet');
    Route::get('game/list',[UserGameController::class, 'GameList'])->name('GameList');
    Route::any('user/{id?}/play-game/{game_type?}',[UserGameController::class, 'playGameView'])->name('user.playGame');
    Route::post('user/play-gameStore',[UserGameController::class, 'playGameStore'])->name('user.playGame.store');
    Route::get('user/play-game/history',[UserGameController::class, 'playGameHistory'])->name('user.playGame.history');
    Route::get('user/play-game/dashboard/{id?}',[UserGameController::class, 'playGameDashboard'])->name('user.playGame.dashboard');

    Route::get('user/previous-game',[UserGameController::class, 'previousGame'])->name('user.previousGame');
});
//End User Game play Route Here

  //Start Partner Dashboard Route Here
  Route::group(['middleware' => ['auth', 'checkRole:Partner'], 'prefix' => 'partner'], function () {
    Route::get('dashboard', [PartnerController::class,'index'])->name('partner.dashboard');
    Route::get('game/create-game',[PartnerController::class, 'GameCreateView'])->name('partner.GameCreateView');
     Route::post('game/create-game',[PartnerController::class, 'GameCreateStore'])->name('partner.GameCreateStore');
    Route::get('game/game-history',[PartnerController::class, 'GameHistory'])->name('partner.GameHistory');
    Route::get('game/{id?}/settings',[PartnerController::class, 'GameSettings'])->name('partner.GameSettings');
    Route::get('/game',[PartnerController::class, 'DataFetch'])->name('partner.DataFetch');

});
//End Partner Dashboard Route Here


 //Start Agent Dashboard Route Here
 Route::group(['middleware' => ['auth', 'checkRole:Agent'], 'prefix' => 'agent'], function () {
     Route::get('dashboard', [AgentController::class,'index'])->name('agent.dashboard');
     Route::get('game/create-user',[AgentController::class, 'UserCreateView'])->name('agent.UserCreateView');
     Route::post('game/create-user',[AgentController::class, 'UserCreateStore'])->name('agent.UserCreateStore');
     Route::get('game/edit-user/{user_id?}',[AgentController::class, 'UserEditView'])->name('agent.UserEditView');
     Route::post('game/edit-user/{user_id?}',[AgentController::class, 'UserEditStore'])->name('agent.UserEditStore');
     Route::get('game/user-history',[AgentController::class, 'UserHistory'])->name('agent.UserHistory');
     Route::post('game/delete-user/{user_id?}',[AgentController::class, 'UserDestroy'])->name('agent.UserDestroy');
});
//End Agent Dashboard Route Here

Route::group(['middleware' => ['auth', 'checkRole:Admin']], function () {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('analysts', AnalystController::class);
    Route::resource('videos', VideosController::class);
    Route::resource('contest', ContestController::class);
    Route::get('contest/uploda-result/{id?}', [ContestController::class, 'ContestUploadResult'])->name('contest.upload.result');
    Route::post('contest/uploda-result/{id?}', [ContestController::class, 'ContestUploadResultStore'])->name('contest.upload.result.store');
    Route::get('contest/aproved/{id?}', [ContestController::class, 'approveContest'])->name('contest.aproved');
    Route::get('prize/distribution', [ContestController::class, 'prizeDistribution'])->name('contest.prizedistribution');
    Route::get('prize/{id?}', [ContestController::class, 'prizeDistributionView'])->name('contest.prize');

    Route::get('contest-answer', [ContestController::class, 'contestAnswer'])->name('contest.answer');
    Route::get('contest-answer-edit/{id?}', [ContestController::class, 'editAnswer'])->name('contest.editanswer');
    Route::post('contest-answer-save/{id?}', [ContestController::class, 'saveContestAns'])->name('contest.editanswersave');
    Route::resource('user_contest', UserContestController::class);
    Route::resource('wallets', WalletController::class);
    Route::resource('user_kyc', UserKycController::class);
    Route::resource('post', PostController::class);
    Route::get('wallets/{wallet}', [WalletController::class, 'show'])->name('wallets.show');

    Route::get('videos/aproved/{id?}', [VideosController::class, 'approveVideos'])->name('videos.aproved');
    Route::get('analysts/aproved/{id?}', [AnalystController::class, 'approveAnalyst'])->name('analysts.aproved');
    Route::get('analyst/account', [AccountController::class, 'index'])->name('account.index');
    Route::get('notification', [ContestController::class, 'notificationView'])->name('notification.create');
    Route::get('notification-list', [ContestController::class, 'notificationList'])->name('notification.index');
    Route::get('leader-board', [ContestController::class, 'leaderBoardList'])->name('leaderboard');
    Route::get('winners', [ContestController::class, 'winnerList'])->name('winnerlist');
    //Start User Management Route Here
    //Route::resource('products', ProductController::class);
    Route::resource('questions', QuestionsController::class);
    Route::resource('answers', AnswersController::class);
    Route::resource('call-logs', CallLogController::class);
    Route::resource('profiles', AnalystProfileController::class);
    Route::resource('banners', AnalystBannerController::class);
    Route::resource('banner', BannerController::class);

});

//Start some common group route here
Route::group(['middleware' => ['auth', 'checkRole:User,Partner,Agent']], function () {
    Route::resource('bank-accounts', BankAccountController::class);
});


//End some common group route here

Route::get('matka/test', [VideosController::class, 'matkaTest']);
Route::get('base64ToString', [UserController::class, 'decodeBase64']);

app/Http/Controllers/Admin/AgentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\{User, UserDetail, Videolist, Category, Subcategory, VideoSubcategory, Genre, VideoGenre, Contest, ContestData, ContestResult, UserContest, ContestWinner, LeaderBoard, UserContestWinloss, Notification, Wallet, UserWallet, UserGame};
use Spatie\Permission\Models\Role;
use Auth;
use DB;
use Hash;
use Exception;
use File;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Validation\ValidationException;

class AgentController extends Controller
{
    private $today;
    public function __construct()
    {
        $this->today = Carbon::today();
    }
    /**
     * Display Agent Dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request){
        $user = Auth::user();
        $game = Contest::get();
        // dd($game);
        $details = UserGame::get();
        // dd($details);


        // $users = User::where('created_by',$user->id)->orderBy('id','desc')->get();
        return view('admin.agent-dashboard.dashboard',compact('details','game'));
    }

    /**
     * Display the file of Create User Create Form View.
     *
     * @return \Illuminate\Http\Response
     */
    public function UserCreateView(Request $request){

        return view('admin.agent-dashboard.user_create');
    }

     /**
     * Method for store user data
     *
     * @return \Illuminate\Http\Response
     */
    public function UserCreateStore(Request $request){
        $user = Auth::user();
        $this->validate($request, [
            'name' => 'required',
            //'email' => 'required|email|unique:users,email',
            'mobile' => 'required|numeric|digits:10|unique:users,mobile',
        ],[
            //'email.unique' => 'This Email Already Exists !',
            'mobile.unique' => 'This Mobile Already Exists !',
        ]);
        //dd($request->all());
        DB::beginTransaction();
        try {
            $input = $request->all();
            $input['password'] = Hash::make('123456789');
            $input['created_by'] = $user->id;
            $user_createtd = User::create($input);
            $user_createtd->assignRole('User');
            //insert data in userdetail table
            UserDetail::create([
                'user_id' => $user_createtd->id
            ]);
            DB::commit();
            return redirect()->route('agent.UserHistory')->with('success','User created successfully');
        } catch (\Throwable $th) {
             DB::rollback();
            //echo $th ;die;
            return back()->with('danger','Something went wrong');
        }
    }

     /**
     * Display the file of Edit User Form View.
     *
     * @return \Illuminate\Http\Response
     */
    public function UserEditView(Request $request,$user_id=NULL){
        $user = User::find($user_id);
        if (!$user) {
           return redirect()->route('agent.dashboard');
        }
        return view('admin.agent-dashboard.user_edit',compact('user'));
    }

     /**
     * Method for Edit user data
     *
     * @return \Illuminate\Http\Response
     */
    public function UserEditStore(Request $request, $user_id = NULL)
    {
        $user = Auth::user();
        $input = $request->all();
        $this->validate($request, [
            'name' => 'required',
            //'email' => 'required|email|unique:users,email,' . $user_id,
            'mobile' => 'required|numeric|digits:10|unique:users,mobile,' . $user_id,
        ]);

        try {
            DB::beginTransaction();
            // Find the user by ID
            $user = User::find($user_id);
            // Check if the user exists
            if (!$user) {
                return back()->with('danger', 'User not found');
            }
            // Update user data
            $user->update($input);
            // Insert data in userdetail table (assuming you have a UserDetail model and relationship)
            // $user->userDetail()->update([...]);
            DB::commit();
            return redirect()->route('agent.UserHistory')->with('success', 'User updated successfully');
        } catch (\Exception $e) {
            DB::rollback();
            // Log the error for debugging purposes
            // logger()->error($e);
            return back()->with('danger', 'Something went wrong');
        }
    }

    /**
     * Method for Delete Users.
     */
    public function UserDestroy(Request $request, $user_id=NULL){
        try {
            // Find the user by ID
            $user = User::find($user_id);
            // Check if the user exists
            if (!$user) {
                return back()->with('danger', 'User not found');
            }
            User::find($user_id)->delete();
            return back()->with('danger','User deleted successfully !');
        } catch (\Throwable $th) {
            //return $th;
            return back()->with('danger', 'Something went wrong !');
        }

    }

     /**
     * Display the file of User history.
     *
     * @return \Illuminate\Http\Response
     */
    public function UserHistory(Request $request){
        $user = Auth::user();
        $user_history = User::where('created_by',$user->id)->orderBy('id','desc')->get();
        return view('admin.agent-dashboard.user_history',compact('user_history'));
    }


}

resources/views/layouts/agent/app.blade.php
<!DOCTYPE html>
<html lang="en" class="sidebar-large">
  @include('layouts.user_game.head')
  @stack('css')

  <body class="hold-transition sidebar-mini layout-fixed">
    
  <div class="main-wrapper">
       <!-- Header -->
       <!-- @include('layouts.user_game.header') -->
       <!-- /Header -->
       <!-- Sidebar -->
       <!-- @include('layouts.user_game.sidebar') -->
       <!-- /Sidebar -->
       @yield('content')
        @include('layouts.user_game.footer')
       @stack('scripts')
     </div>
  </body>

</html>

resources/views/layouts/agent/flash_msg.blade.php
@if(session('success'))
            <script>
                Swal.fire({
                     title: '{{ session('success') }}',
                    //text: 'You clicked the button!',
                    icon: 'success'
                });
            </script>
        @endif
        
        @if(session('danger'))
            <script>
                Swal.fire({
                     title: '{{ session('danger') }}',
                    //text: 'Something went wrong!',
                    icon: 'error'
                });
            </script>
        @endif

resources/views/layouts/agent/footer.blade.php
<!-- jQuery -->
<script src="{{ asset('ration/assets/js/jquery-3.6.0.min.js') }}"></script>

<!-- Bootstrap Core JS -->
<script src="{{ asset('ration/assets/js/popper.min.js') }}"></script>
<script src="{{ asset('ration/assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Slimscroll JS -->
<script src="{{ asset('ration/assets/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- Select2 JS -->
<script src="{{ asset('ration/assets/js/select2.min.js') }}"></script>
<!-- Custom JS -->
<script src="{{ asset('ration/assets/js/admin.js') }}"></script>

resources/views/layouts/agent/head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <title>@yield('title')</title>
    <!-- Favicons -->
    <link rel="shortcut icon" href="{{ asset('ration/assets/img/favicon.png') }}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ asset('ration/assets/plugins/bootstrap/css/bootstrap.min.css') }}">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="{{ asset('ration/assets/plugins/fontawesome/css/fontawesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('ration/assets/plugins/fontawesome/css/all.min.css') }}">
    
    <!-- Animate CSS -->
    <link rel="stylesheet" href="{{ asset('ration/assets/css/animate.min.css') }}">

    <!-- Main CSS -->
    <!-- <link rel="stylesheet" href="{{ asset('ration/assets/css/admin.css') }}"> -->
    <link rel="stylesheet" href="{{ asset('ration/assets/css/admin1.css') }}">

</head>

resources/views/layouts/agent/header.blade.php
<!-- Header -->
<div class="header">
			<div class="header-left"> 
				<a href="index.html" class="logo logo-small">
					<img src="{{ asset('ration/assets/img/logo-icon.png') }}" alt="Logo" width="30" height="30">
				</a>
			</div>
			<a href="javascript:void(0);" id="toggle_btn">
				<i class="fas fa-align-left"></i>
			</a>
			<a class="mobile_btn" id="mobile_btn" href="javascript:void(0);">
				<i class="fas fa-align-left"></i>
			</a>
			
			<ul class="nav user-menu">
				<!-- Notifications -->
				<li class="nav-item dropdown noti-dropdown">
					<a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
						<i class="far fa-bell"></i>  <span class="badge badge-pill"></span>
					</a>
					<!-- <div class="dropdown-menu dropdown-menu-right notifications">
						<div class="topnav-dropdown-header">
							<span class="notification-title">Notifications</span>
							<a href="javascript:void(0)" class="clear-noti"> Clear All </a>
						</div>
						<div class="noti-content">
							<ul class="notification-list">
								<li class="notification-message">
									<a href="admin-notification.html">
										<div class="media">
											<span class="avatar avatar-sm">
												<img class="avatar-img rounded-circle" alt="" src="{{ asset('ration/assets/img/provider/provider-01.jpg') }}">
											</span>
											<div class="media-body">
												<p class="noti-details">
													<span class="noti-title">Thomas Herzberg have been subscribed</span>
												</p>
												<p class="noti-time">
													<span class="notification-time">15 Sep 2020 10:20 PM</span>
												</p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="admin-notification.html">
										<div class="media">
											<span class="avatar avatar-sm">
												<img class="avatar-img rounded-circle" alt="" src="{{ asset('ration/assets/img/provider/provider-02.jpg') }}">
											</span>
											<div class="media-body">
												<p class="noti-details">
													<span class="noti-title">Matthew Garcia have been subscribed</span>
												</p>
												<p class="noti-time">
													<span class="notification-time">13 Sep 2020 03:56 AM</span>
												</p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="admin-notification.html">
										<div class="media">
											<span class="avatar avatar-sm">
												<img class="avatar-img rounded-circle" alt="" src="{{ asset('ration/assets/img/provider/provider-03.jpg') }}">
											</span>
											<div class="media-body">
												<p class="noti-details">
													<span class="noti-title">Yolanda Potter have been subscribed</span>
												</p>
												<p class="noti-time">
													<span class="notification-time">12 Sep 2020 09:25 PM</span>
												</p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="admin-notification.html">
										<div class="media">
											<span class="avatar avatar-sm">
												<img class="avatar-img rounded-circle" alt="User Image" src="{{ asset('ration/assets/img/provider/provider-04.jpg') }}">
											</span>
											<div class="media-body">
												<p class="noti-details">
													<span class="noti-title">Ricardo Flemings have been subscribed</span>
												</p>
												<p class="noti-time">
													<span class="notification-time">11 Sep 2020 06:36 PM</span>
												</p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="admin-notification.html">
										<div class="media">
											<span class="avatar avatar-sm">
												<img class="avatar-img rounded-circle" alt="User Image" src="{{ asset('ration/assets/img/provider/provider-05.jpg') }}">
											</span>
											<div class="media-body">
												<p class="noti-details">
													<span class="noti-title">Maritza Wasson have been subscribed</span>
												</p>
												<p class="noti-time">
													<span class="notification-time">10 Sep 2020 08:42 AM</span>
												</p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="admin-notification.html">
										<div class="media">
											<span class="avatar avatar-sm">
												<img class="avatar-img rounded-circle" alt="User Image" src="{{ asset('ration/assets/img/provider/provider-06.jpg') }}">
											</span>
											<div class="media-body">
												<p class="noti-details">
													<span class="noti-title">Marya Ruiz have been subscribed</span>
												</p>
												<p class="noti-time">
													<span class="notification-time">9 Sep 2020 11:01 AM</span>
												</p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="admin-notification.html">
										<div class="media">
											<span class="avatar avatar-sm">
												<img class="avatar-img rounded-circle" alt="User Image" src="{{ asset('ration/assets/img/provider/provider-07.jpg') }}">
											</span>
											<div class="media-body">
												<p class="noti-details">
													<span class="noti-title">Richard Hughes have been subscribed</span>
												</p>
												<p class="noti-time">
													<span class="notification-time">8 Sep 2020 06:23 AM</span>
												</p>
											</div>
										</div>
									</a>
								</li>
							</ul>
						</div>
						<div class="topnav-dropdown-footer">
							<a href="admin-notification.html">View all Notifications</a>
						</div>
					</div> -->
				</li>
				<!-- /Notifications -->
				
				<!-- User Menu -->
				<li class="nav-item dropdown">
					<a href="javascript:void(0)" class="dropdown-toggle user-link  nav-link" data-bs-toggle="dropdown">
						<span class="user-img">
							<img class="rounded-circle" src="{{ asset('ration/assets/img/user.jpg') }}" width="40" alt="Admin">
						</span>
					</a>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="javascript:void(0)" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Logout</a>
						<form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
           				</form>
					</div>
				</li>
				<!-- /User Menu -->
				
			</ul>
		</div>
		<!-- /Header -->

resources/views/layouts/agent/sidebar.blade.php
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
 <!-- Sidebar Menu -->
		<?php
          $current_route = Route::currentRouteName();
          ?>
<div class="sidebar" id="sidebar">
        
        <div class="sidebar-inner slimscroll">
          <div id="sidebar-menu" class="sidebar-menu">
            <ul>
              <li>
                <a href="{{ route('agent.dashboard') }}"
                  ><i class="fas fa-columns"></i> <span>Dashboard</span></a
                >
              </li>

              <li>
                <a href="{{ route('agent.UserCreateView') }}"
                  ><i class="fas fa-columns"></i> <span>Create User</span></a
                >
              </li>

              <li>
                <a href="{{ route('agent.UserHistory') }}"
                  ><i class="fas fa-history"></i> <span>Your Users</span>
                  <span></span
                ></a>
              </li>
              <li class="submenu">
                <a href=""
                  ><i class="fas fa-wallet"></i> <span>wallet</span>
                  <span class="menu-arrow"></span
                ></a>
                <ul style="display: none">
                <li><a href="{{ route('bank-accounts.index') }}">Bank Details</a></li>
                  <li><a href="javascript:void(0)">Wallet History</a></li>
                </ul>
              </li>
              <li>
                <a  href="javascript:void(0)" onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i class="far fa-window-close"></i> <span>Logout</span></a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
           				</form>
              </li>
            </ul>
          </div>
        </div>
      </div>
		<!-- /Sidebar -->